### ISSUE TITLE
Allow String for Date DataType

### ISSUE THREAD

**Issue by dcphanke** [Prefinem/nativemodels#24]

**Comment by dcphanke** [comment]
Just add a date parse.   Like you did with int

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dcphanke** [comment]
I am passing in a json file to the model and the date is a string '2018-10-01 00:00:00'

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Prefinem** [comment]
just pass in date like so `new Date(string)`

**Comment by dcphanke** [comment]
I am importing a json object into the model.  I cant a just the value before it hits your model

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Prefinem** [comment]
Done part of version 1.6.0
